### ISSUE TITLE
add smoke particle effect to campfire

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/Catch.ioProjectBoard#24]
## Feature Subtasks

- [x] import a smoke particle sprite
- [x] add a particle object that makes a chunk of smoke go up a campfire

## Description

add a smoke particle effect to the campfire environmental object.
it should look something like this, but the smoke should not go too high.
![giphy](https://user-images.githubusercontent.com/40356749/90039138-36a96b80-dd01-11ea-98ba-d077078a6fec.gif)
you can look at this tutorial to see how to make a 2D particle effect in Unity just in case https://www.youtube.com/watch?v=_z68_OoC_0o

## Difficulty

1/10

## Estimated Implementation Time

- Optimistic - {how long this will take to finish all the subtasks at the very least}
- Normal - {how long this will take to finish all the subtasks on average work time}
- Pessimistic - {how long this will take to finish all the subtasks at most}

## Work Start Date

{when will the implementation will start}

**Comment by ange-p916** [comment]
how to replace sprite:
find campfireA in project folder > edit prefab > open smoke effect child > open texture sheet animation in attributes tab > replace smokeeffect sprite
